### ISSUE TITLE
[chart/redis_ha][REQUEST] Small improvements

### ISSUE THREAD

**Issue by haljin** [DandyDeveloper/charts#106]
I have a couple of small requests, most of which I could make a PR myself on, but I'd like to hear from maintainers first. :)

1. Our K8s cluster requires containers to define a `readinessProbe`. None of the containers in this chart do that right now. The readiness probe could just be the same `ping` that the `livenessProbe` does. I had to fix that on my fork and I'd love to make a PR on that.

2. Network policy - While those are not explicitly enforced they are mandated for our production environment. I can of course create one outside of this chart, but it'd be nice to have it as part of it. The chart could define a label that pods allowed to connect Redis/HAProxy must have in order to be allowed. I am however unsure exactly how the HAProxy <-> Redis connectivity works so not 100% on how to define the policy correctly (In our deployment we skipped HAProxy).

3. I have noticed that the cluster is in an incorrect state if you configure it with:
```yaml
redis:
    tlsReplication: true
    tlsPort: 6380
    port: 6379
  sentinel:
    tlsReplication: true
    tlsPort: 26380
    port: 26379
    auth: true
    existingSecret: <redacted>
    authKey: redis-password
    config:
      down-after-milliseconds: 5000
      failover-timeout: 10000
      parallel-syncs: 5
      maxclients: 10000
  auth: true
  existingSecret: <redacted>
  authKey: redis-password
  tls:
    secretName: <redacted>
    certFile: redis-crt
    keyFile: redis-key
    caCertFile: root-ca
```

The problem occurs when both `port` and `tlsPort` are defined. The Sentinels attempt to communicate with each other on the non-TLS port and that does not succeed. After `down-after-milliseconds` time all Sentinels assume the other Sentinels are gone. Thus they can never reach a quorum and perform a successful failover. After I reconfigured with:

```yaml
  redis:
    tlsReplication: true
    tlsPort: 6380
    port: 0
  sentinel:
    tlsReplication: true
    tlsPort: 26380
    port: 0
```

Things started working properly. I'm not sure what is the intention here, but at least some documentation warning that such misconfiguration is possible would be nice.

**Comment by DandyDeveloper** [comment]
@haljin 

1. I have just merged a readinessProbe PR that should do what you've asked (I think).
2. There's an issue here with a good example: https://github.com/DandyDeveloper/charts/issues/83 which I do agree with now. Would welcome contributions from someone actively using them. If not, I'll add it to my todo. 
3. This looks to be an artifact of the recent addition of the tls implementation. I thought Redis / Sentinel would prio port but seems to not be the case. That'll need fixing for sure. Thank you for the workaround in the meantime.

**Comment by haljin** [comment]
Awesome, thanks! 

Here's a network policy I made for our deployment (note that redis-ha is the dependency chart to this one) :

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-redis-policy
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
      app: redis-ha
  policyTypes:
    - Ingress
    - Egress
  ingress: 
    - from:
      - podSelector:
          matchLabels:
            release: {{ .Release.Name }}
            app: redis-ha
      ports:
        - port: {{ .Values.redis-ha.tlsPort }}
          protocol: TCP
        - port: {{ .Values.redis-ha.sentinel.tlsPort }}
          protocol: TCP    
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}
      ports:
        - port: {{ .Values.redis-ha.tlsPort }}
          protocol: TCP
        - port: {{ .Values.redis-ha.sentinel.tlsPort }}
          protocol: TCP   
    - from: 
      - podSelector:
          matchLabels:
            release: {{ .Release.Name }}
      ports:
      - port: {{ .Values.redis-ha.metrics.port }}
        protocol: TCP
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: redis-ha
            release: {{ .Release.Name }}
      ports:
        - port: {{ .Values.redis-ha.tlsPort }}
          protocol: TCP
        - port: {{ .Values.redis-ha.sentinel.tlsPort }}
          protocol: TCP          
    - to: []
      ports:
        - port: 53
          protocol: UDP
```

This is without HAProxy however, as we are not using that and I am not quite sure what does that require
