### ISSUE TITLE
[chart/redis-ha][BUG] Permission denied when opening files needed for syncing

### ISSUE THREAD

**Issue by ianks** [DandyDeveloper/charts#13]
### Description

When running the chart, we started encountering a ton of `NOREPLICAS Not enough good replicas to write` errors in our application logs. Upon further investigation, it looks like Redis does not have permissions to open files that are needed for syncing since we are seeing `Opening the temp file needed for MASTER <-> REPLICA synchronization: Permission denied` and `Failed opening the RDB file root (in server root dir /etc/crontabs) for saving: Permission denied` in our logs.

### Our Config

```yaml
---
haproxy:
  enabled: true
  stickyBalancing: true
  service:
    type: LoadBalancer

rbac:
  create: true

sysctlImage:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -xc
    - |-
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled

persistentVolume:
  enabled: true
  storageClass: singlewriter-standard
  size: 50Gi

exporter:
  enabled: true
  serviceMonitor:
    enabled: true
```

### Logs

```
I 2020-04-09T13:13:53.931471711Z 1:S 09 Apr 2020 13:13:53.931 # Opening the temp file needed for MASTER <-> REPLICA synchronization: Permission denied
 
I 2020-04-09T13:13:53.931719338Z 1:S 09 Apr 2020 13:13:53.931 * 1 changes in 900 seconds. Saving...
 
I 2020-04-09T13:13:53.931890231Z 1:M 09 Apr 2020 13:13:53.931 # Connection with replica 10.0.13.151:6379 lost.
 
I 2020-04-09T13:13:53.932284469Z 1:S 09 Apr 2020 13:13:53.932 * Background saving started by pid 1046
 
I 2020-04-09T13:13:53.932351310Z 1046:C 09 Apr 2020 13:13:53.932 # Failed opening the RDB file root (in server root dir /etc/crontabs) for saving: Permission denied
 
I 2020-04-09T13:13:53.932536819Z 1:M 09 Apr 2020 13:13:53.932 # Connection with replica 10.0.5.223:6379 lost.
 
I 2020-04-09T13:13:53.939283142Z 1:S 09 Apr 2020 13:13:53.931 # Opening the temp file needed for MASTER <-> REPLICA synchronization: Permission denied
 
I 2020-04-09T13:13:53.939322056Z 1:S 09 Apr 2020 13:13:53.931 * 1 changes in 900 seconds. Saving...
 
I 2020-04-09T13:13:53.939328666Z 1:S 09 Apr 2020 13:13:53.931 * Background saving started by pid 1448
 
I 2020-04-09T13:13:53.939334871Z 1448:C 09 Apr 2020 13:13:53.933 # Failed opening the RDB file root (in server root dir /etc/crontabs) for saving: Permission denied
 
I 2020-04-09T13:13:53.947186305Z 1:M 09 Apr 2020 13:13:53.946 # Background transfer error
 
I 2020-04-09T13:13:54.032355153Z 1:S 09 Apr 2020 13:13:54.032 # Background saving error
 
I 2020-04-09T13:13:54.033385622Z 1:S 09 Apr 2020 13:13:54.033 # Background saving error
 
```

### Summary

We are currently looking for a solution to this problem. Are we doing something wrong in our config? Also, let me know if you have any other questions, happy to help as much as I can!

Best,
Ian
