### ISSUE TITLE
[chart/redis-ha][BUG] - NetworkPolicy egress should include DNS ports

### ISSUE THREAD

**Issue by sean-mcgimpsey** [DandyDeveloper/charts#151]
**Describe the bug**
The network policy implementation should include DNS ports. These are needed for the config-init container, as well as the split-brain-fix container. 

Currently the networkPolicy is unusable

**To Reproduce**
1. Enable network policy with the base values
2. Check the logs of the config-init container

**Expected behavior**
DNS resolution should work.

**Additional context**
Workaround is to add the following to egress rules; 
```
      - ports:
          - port: 53
            protocol: TCP
          - port: 53
            protocol: UDP
```
