### ISSUE TITLE
[chart/redis-ha] allow creation of network policies for haproxy

### ISSUE THREAD

**Issue by dani-CO-CN** [DandyDeveloper/charts#255]
**Is your feature request related to a problem? Please describe.**
i use this helm chart as a dependency in the argocd helm chart, currently i could not find away to create network policies for haproxy.

**Describe the solution you'd like**
add a network policy template for haproxy pods to the helm chart, this would allow me to just inject my ingress/egress blocks as values.

```
haproxy:
  netpol:
    enabled: true
    ingress:
    - from:
      - podSelector:
          matchLabels:
            app: argocd
      ports:
      - port: the_redis_port
        protocol: TCP
```

**Describe alternatives you've considered**
