### ISSUE TITLE
[charts/redis-ha][BUG] EOF errors after upgrading to v4.5.3

### ISSUE THREAD

**Issue by alexmt** [DandyDeveloper/charts#26]
**Describe the bug**

After upgrading chart from v3.3.1 to v4.5.3 the proxy is unable to connect to redis and all requests are failing with EOF error. As a workaround, we've "restarted" redis stateful set and proxy pods. A couple of minutes after the restart issue got resolved.

**To Reproduce**

Unfortunately, no clear steps to reproduce. I've once observed it twice after upgrading ~40 redis HA clusters. Several users of our product reported the same. 

**Expected behavior**
It is expected to see intermittent issue during the upgrade but no manual intervention should be required. 

**Additional context**
Please find proxy and redis/sentinel logs in the attached files. 

[ha-proxy.log](https://github.com/DandyDeveloper/charts/files/4618223/ha-proxy.log)
[redis-pod.log](https://github.com/DandyDeveloper/charts/files/4618224/redis-pod.log)

**Comment by alexmt** [comment]
The most important question is: do you think the issue related to v3.3.1 -> v4.5.3 upgrade or could happen after upgrade is done (e.g. due to pod restart)?

**Comment by DandyDeveloper** [comment]
@alexmt I am fairly confident this is due to the nature of the way the master gets terminated due to an upgrade. I'll see if we can perform a more graceful shutdown. This might resolve things.

**Comment by DandyDeveloper** [comment]
@alexmt 
```yaml
      - name: redis-exporter
        image: "oliver006/redis_exporter:v1.3.2-arm64"
        imagePullPolicy: IfNotPresent
        args:
        env:
          - name: REDIS_ADDR
            value: redis://localhost:6379
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15
        resources:
          {}
        ports:
          - name: exporter-port
            containerPort: 9121
      volumes:
      - name: config
        configMap:
          name: RELEASE-NAME-redis-ha-configmap
```

It looks like it's deployed. Are you certain the sidecar container isn't created?
