### ISSUE TITLE
redis-ha-4.23.0 - problems with ssh restore

### ISSUE THREAD

**Issue by yoshi314** [DandyDeveloper/charts#266]
**Describe the bug**
I attempted to deploy helm chart with restore via ssh by adding 

```
restore:
  ssh:
    source: login@server:~/automatic-cas-sandbox-memorydb-2024-01-03-05-04-0001.rdb
    key: "-----BEGIN OPENSSH PRIVATE KEY-----\n(....)\n-----END OPENSSH PRIVATE KEY-----"
```

What happens is 

``` 
test-rec-redis-redis-ha-server-0 restore-ssh sh: can't create key: Permission denied
- test-rec-redis-redis-ha-server-0 › restore-ssh
+ test-rec-redis-redis-ha-server-0 › restore-ssh
```

I could use some help with debugging this.
