### ISSUE TITLE
redis-ha - Can't see Prometheus metrics

### ISSUE THREAD

**Issue by dbeilin** [DandyDeveloper/charts#269]
I deployed the community kube-stack on my local KinD cluster with the default settings using Helm.
Then I deployed redis-ha with the following values file:
```yaml
## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
image:
  repository: redis
  tag: 7.2.4-alpine
  pullPolicy: IfNotPresent

## replicas number for each component
replicas: 1

## Custom labels for the redis pod
labels: {}

## Custom labels for redis service
serviceLabels: {}

# Prometheus exporter specific configuration options
exporter:
  enabled: true
  image: oliver006/redis_exporter
  tag: v1.57.0
  pullPolicy: IfNotPresent

  # prometheus port & scrape path
  port: 9121
  portName: exporter-port
  scrapePath: /metrics

  # Address/Host for Redis instance. Default: localhost
  # Exists to circumvent issues with IPv6 dns resolution that occurs on certain environments
  ##
  address: localhost

  serviceMonitor:
    # When set true then use a ServiceMonitor to configure scraping
    enabled: true
    # Set the namespace the ServiceMonitor should be deployed
    namespace: "redis"
    # Set how frequently Prometheus should scrape
    interval: 10s
    # Set path to redis-exporter telemtery-path
    telemetryPath: /metrics
    # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
    labels: {}
    # Set timeout for scrape
    # timeout: 10s
    # Set additional properties for the ServiceMonitor endpoints such as relabeling, scrapeTimeout, tlsConfig, and more.
    endpointAdditionalProperties: {}
```

My Prometheus is running in the `prometheus` namespace while the Redis app was deployed to the `redis` namespace. I see all of the resources and everything looks normal, but when I go to Prometheus I don't see my Redis target, or even redis related metrics if I try to type some expression.

The Prometheus operator doesn't show any errors in the logs, same for the redis-exporter.
Any help would be appreciated.
