### ISSUE TITLE
[charts/redis-ha][BUG] Exporter not deployed

### ISSUE THREAD

**Issue by slaecker** [DandyDeveloper/charts#27]
**Describe the bug**
When "exporter.enabled" is set to "true" it is not deployed.

**To Reproduce**

1. Enable the exporter in values.yaml
```
exporter:
  enabled: true
  image: oliver006/redis_exporter
  tag: v1.3.5-arm64
```
2. Install the chart
```
helm install --namespace database redis-ha dandydev/redis-ha -f database/redis-ha-helm-values.yaml
```
3. Check the pods
```
kubectl get -n database pods
kubectl get -A pods | grep redis
kubectl get -A pods | grep exporter
```

**Expected behavior**
The exporter gets deployed.

**Additional context**
I'm running this on K3S on a 4 node Raspberry Pi 4 cluster on Raspbian Buster running the aarch64 kernel.

**Comment by DandyDeveloper** [comment]
@slaecker I'll take a look at this, it's a weird one. Because it's working locally for me. 

Can you try templating `helm template .` and share the output (format as best you can please!)

**Comment by DandyDeveloper** [comment]
@slaecker 

```yaml
      - name: redis-exporter
        image: "oliver006/redis_exporter:v1.3.2-arm64"
        imagePullPolicy: IfNotPresent
        args:
        env:
          - name: REDIS_ADDR
            value: redis://localhost:6379
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15
        resources:
          {}
        ports:
          - name: exporter-port
            containerPort: 9121
      volumes:
      - name: config
        configMap:
          name: RELEASE-NAME-redis-ha-configmap
```

It looks like it's deployed. Are you certain the sidecar container isn't created?
