### ISSUE TITLE
[chart/redis-ha Add pod meta label to master

### ISSUE THREAD

**Issue by tschirmer** [DandyDeveloper/charts#298]
Would like to see a pod label added onto the master, we can then set a pod disruption budget specifically for the current master, to prevent split brain when nodes go down or the kubernetes descheduler is run.

**Comment by DandyDeveloper** [comment]
@tschirmer Something like `additionalLabels` just specific to the master / slaves:

```
redis:
  master:
     additionalLabels: {}
  slaves:
     additionalLabels: {}
```
