### ISSUE TITLE
[redis-ha][BUG] misleading hardAntiAffinity values

### ISSUE THREAD

**Issue by beniamin** [DandyDeveloper/charts#31]
**Describe the bug**
The behavior of hardAntiAffinity, when is set to `false`, is really misleading.
The template redis-ha-statefulset.yaml for podAffinity looks like:
```yaml
 podAntiAffinity:
    {{- if .Values.hardAntiAffinity }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: {{ template "redis-ha.name" . }}
                  release: {{ .Release.Name }}
                  {{ template "redis-ha.fullname" . }}: replica
              topologyKey: kubernetes.io/hostname
    {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: {{ template "redis-ha.name" . }}
                  release: {{ .Release.Name }}
                  {{ template "redis-ha.fullname" . }}: replica
              topologyKey: kubernetes.io/hostname
    {{- end }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app:  {{ template "redis-ha.name" . }}
                    release: {{ .Release.Name }}
                    {{ template "redis-ha.fullname" . }}: replica
                topologyKey: failure-domain.beta.kubernetes.io/zone
    {{- end }}
```

**To Reproduce**
1. set hardAntiAffinity to false for redis or haproxy
2. upgrade/install release using helm upgrade/helm install
3. check podAntiAffinity

**Expected behavior**
I expect, by setting hardAntiAffinity to false, that `requiredDuringSchedulingIgnoredDuringExecution` to be changed with `preferredDuringSchedulingIgnoredDuringExecution` and nothing more.
**Additional context**
The resulted config will have podAntiAffinity set with two `preferredDuringSchedulingIgnoredDuringExecution` keys. First contains `topologyKey: kubernetes.io/hostname` and the last one contains `topologyKey: failure-domain.beta.kubernetes.io/zone`.
When the resulted yamls are applied to k8s cluster only the last one remains.

This behaviour is misleading because I expect that pods will be spawned on different nodes, if possible, but with `topologyKey: failure-domain.beta.kubernetes.io/zone` almost all pods may end up on the same node.
