### ISSUE TITLE
[chart/redis-ha][BUG] haproxy config doesn't support redis port deactivation (0)

### ISSUE THREAD

**Issue by OpenGuidou** [DandyDeveloper/charts#310]
**Describe the bug**
When activating TLS on redis side and deactivating non-TLS port (setting it to 0), part of the haproxy config doesn't work:

https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/_configs.tpl#L537
It still tries to bind to port 0 and fails.

`bind: invalid port '0'`

**Expected behavior**
It should use the redis tlsPort as soon as the redis port is 0, as everywhere else in the config.

**Comment by DandyDeveloper** [comment]
@OpenGuidou Can you walk me through the logic on this? 

You want Redis enabled with TLS and with HAProxy enabled and the values in your case is resulting in the port being set to 0? 

Can you provide a condensed / relevant snippet of your `values.yaml`? I want to make sure I understand the problem so I can review the PR.

**Comment by OpenGuidou** [comment]
Hi @DandyDeveloper,
Thanks for taking the time to review my PR.

The goal would be, having ha-proxy enabled, to activate TLS on redis and deactivate the non-tls port.

Here is an extract of the values:
```yaml
redis:
  port: 0
  tlsPort: 6379
  tlsReplication: true
  authClients: optional
tls:
  secretName: redis-cert
  certFile:tls.crt
  keyFile: tls.key
  caCertFile: ca.crt
sentinel:
  tlsPort: 26379
  port: 0
  tlsReplication: true
haproxy:
  enabled: true
  tls:
    enabled: true
    secretName: haproxy-cert
    keyName: "tls.key"
```
