### ISSUE TITLE
[chart/redis-ha][BUG] Kubernetes selector matchLabels for PodDisruptionBudget on Haproxy is wrong

### ISSUE THREAD

**Issue by Daniel12377** [DandyDeveloper/charts#330]
**Describe the bug**

We encountered an error when setting up PodDisruptionBudget for HAProxy. The problem is that in the redis-haproxy-pdb.yaml file, the string "-haproxy" is appended under matchLabels for app (`app: {{ template "redis-ha.name" . }}-haproxy`), while the actual HAProxy deployment's app label is missing this suffix (app: redis-ha). This mismatch prevents the PodDisruptionBudget from correctly selecting and managing the HAProxy pods.

**To Reproduce**
1. Clone the Repo
2. Change the file redis-ha/values.yaml 
    Set haproxy.enabled: true
    Set haproxy.podDisruptionBudget.maxUnavailable: 1
3. Check the labels on the redis-haproxy-deployment 
```
helm template --debug redis-ha --values "redis-ha/values.yaml" | yq 'select((.kind == "Deployment") and (.metadata.name == "release-name-redis-ha-haproxy"))'
# Source: redis-ha/templates/redis-haproxy-deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: release-name-redis-ha-haproxy
  namespace: "default"
  labels:
    app: redis-ha
    heritage: "Helm"
    release: "release-name"
    chart: redis-ha-4.33.7
```
4. Check the selector matchLabels for PodDisruptionBudget
```
helm template --debug redis-ha --values "redis-ha/values.yaml" | yq 'select((.kind == "PodDisruptionBudget"))'
# Source: redis-ha/templates/redis-haproxy-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-redis-ha-haproxy-pdb
  namespace: "default"
  labels:
    app: redis-ha
    heritage: "Helm"
    release: "release-name"
    chart: redis-ha-4.33.7
spec:
  selector:
    matchLabels:
      release: release-name
      app: redis-ha-haproxy
  maxUnavailable: 1
```

**Expected behavior**
In the deployment labels, the key "app" has the same value (redis-ha-haproxy) as in the PodDisruptionBudget.
```
# Source: redis-ha/templates/redis-haproxy-deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: release-name-redis-ha-haproxy
  namespace: "default"
  labels:
    app: redis-ha-haproxy
    heritage: "Helm"
    release: "release-name"
    chart: redis-ha-4.33.7
```

**Additional context**
