### ISSUE TITLE
[chart/redis-ha][BUG] redis_exporter does not trust the redis server in TLS mode

### ISSUE THREAD

**Issue by JorenZ** [DandyDeveloper/charts#68]
**Describe the bug**
When TLS is enabled on redis, the redis_exporter cannot connect to the redis server.
This is because the redis_exporter does not receive the redis server CA, so it cannot validate the server's certificate.

**To Reproduce**
We rolled out the helm chart with 
```yaml
redis:
  port: 0
  tlsPort: 6379
  tlsReplication: true
sentinel:
  port: 0
  tlsPort: 26379
  tlsReplication: true
exporter:
  enabled: true
  sslEnabled: true
tls:
  secretName: mysecret-tls
  certFile: tls.crt
  keyFile: tls.key
  caCertFile: ca.crt
```
and found the following redis_exporter debug logs (I manually set it to debug mode with `REDIS_EXPORTER_DEBUG: "true"`)
```
level=debug msg="Trying DialURL(): rediss://localhost:6379"
level=debug msg="DialURL() failed, err: x509: certificate signed by unknown authority"
level=debug msg="Trying: Dial(): rediss localhost:6379"
level=error msg="Couldn't connect to redis instance"
level=debug msg="connectToRedis( rediss://localhost:6379 ) err: dial rediss: unknown network rediss"
level=debug msg="scrapeRedisHost() done"
```

**Expected behavior**
The redis_exporter can connect to a redis server in TLS mode.

**Additional context**
Adding 
```yaml
- name: REDIS_EXPORTER_TLS_CA_CERT_FILE
  value: /tls-certs/{{ .Values.tls.caCertFile }}```
```
to the redis HA statefulset node_exporter's environment fixed the issue for me.
As per [the node_exporter documentation](https://github.com/oliver006/redis_exporter), this allows it to verify the server:

```
level=debug msg="Trying DialURL(): rediss://localhost:6379"
level=debug msg="connected to: rediss://localhost:6379"
level=debug msg="connecting took 0.123456 seconds"
[...]
```
