### ISSUE TITLE
[chart/redis-ha] Implement network policies in the chart

### ISSUE THREAD

**Issue by pierluigilenoci** [DandyDeveloper/charts#83]
**Is your feature request related to a problem? Please describe.**
We use network policy in our clusters and the Redis don't work if Network Policy are defined inside the namespace where Redis is running.

**Describe the solution you'd like**
I would like the to have proper Network Policies to make Redis work in case of a policy like this:

```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default.deny-all-ingress-traffic
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Ingress
```

**Describe alternatives you've considered**
There is no alternative

**Additional context**
Ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by DandyDeveloper** [comment]
@pierluigilenoci What kind of Network policy do you expect here? 

I'm on the fence with this as people would be better adding this in their own chart and using redis-ha as a dependency and deploying network policies via the templates in the parent chart. 

My concern is network policies have a fair bit of flexibility and are dependent on the users cluster config. We could go for a generic "one size fits all" for Redis / HAProxy. I'd like your thoughts on this.

**Comment by pierluigilenoci** [comment]
Hi @DandyDeveloper sorry for the delay in answering.

What I expect from the chart would be an option like `networkPolicy: false`. 

If you set it to `true` a policy like this should be created:

```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: <whatyouprefer>
  namespace: <namespacewhereyouinstallredis>
spec:
  podSelector:
    matchLabels:
      app: redis-ha
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: redis-ha
        - podSelector:
            matchLabels:
              app: redis-ha-haproxy
```

This is independent of any configuration outside the chart, at least I think.

**Comment by pierluigilenoci** [comment]
Eventually, by adding an additional parameter in the values, you could specify the label that the Redis clients must have.

Values.yaml
```yaml
podClientSelector: "app.kubernetes.io/name: <whatever>"
```
 
Then define a policy like this: 
```yaml
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: <whatyouprefer>
  namespace: <namespacewhereyouinstallredis>
spec:
  podSelector:
    matchLabels:
      app: redis-ha-haproxy
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: redis-ha-haproxy
        - podSelector:
            matchLabels:
              {{ .Values.podClientSelector . | indent 14 }}
```

This is just an idea, in case it should be done a little better but I hope you understand the meaning.
